# Generated by Django 4.1.4 on 2022-12-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_staff_agentsinfo_organization'),
        ('leads', '0002_status_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddata',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentsinfo'),
        ),
        migrations.AddField(
            model_name='leaddata',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaddata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.status'),
        ),
    ]
