# Generated by Django 4.1.4 on 2022-12-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leaddata_agent_leaddata_organization_leaddata_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='category',
            new_name='status',
        ),
    ]
