# Generated by Django 4.1.4 on 2022-12-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0004_rename_category_comments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddata',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigncollection'),
        ),
        migrations.AddField(
            model_name='leaddata',
            name='campaign_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaigns'),
        ),
    ]
