# Generated by Django 4.1.4 on 2022-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leaddata_campaign_leaddata_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='lead_name',
            field=models.CharField(max_length=30),
        ),
    ]
