# Generated by Django 4.1.4 on 2022-12-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_leaddata_email_alter_leaddata_lead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddata',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaddata',
            name='lead_name',
            field=models.CharField(max_length=100),
        ),
    ]
