# Generated by Django 4.1.4 on 2022-12-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_permissionstate_user_userposition_agentsinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentsinfo',
            old_name='staff',
            new_name='organization',
        ),
    ]
