# Generated by Django 4.1.4 on 2022-12-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_staff_agentsinfo_organization'),
        ('campaigns', '0003_remove_campaigncollection_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='organization',
        ),
        migrations.AddField(
            model_name='campaigncollection',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.userprofile'),
            preserve_default=False,
        ),
    ]
