# Generated by Django 4.1.4 on 2022-12-20 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_staff_agentsinfo_organization'),
        ('campaigns', '0004_remove_campaigns_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncollection',
            name='organization',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigns',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.userprofile'),
            preserve_default=False,
        ),
    ]
