# Generated by Django 4.1.4 on 2022-12-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaigncollection_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncollection',
            name='campaign',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
