# Generated by Django 4.1.4 on 2022-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaigncollection_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncollection',
            name='duplicates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
